# Generated by Django 4.1.7 on 2023-02-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_created_by_note_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user_id',
            new_name='created_by',
        ),
    ]
